Repository AY2223S2-CS2113-T11-2/tp, pull requests merged in 2023-03, with the labels that each got.

#15 Add junit tests
  .gitignore
  src/main/java/seedu/penus/exceptions/InvalidFormatException.java
  src/main/java/seedu/penus/exceptions/InvalidGradeException.java
  src/main/java/seedu/penus/exceptions/InvalidModuleException.java
  src/main/java/seedu/penus/exceptions/InvalidTaskException.java
  src/main/java/seedu/penus/modules/Grade.java
  src/main/java/seedu/penus/modules/Module.java
  src/main/java/seedu/penus/modules/ModuleList.java
  src/main/java/seedu/penus/parser/CommandParser.java
  src/main/java/seedu/penus/parser/ModuleParser.java
  src/test/java/seedu/penus/ParserTest.java
  src/test/java/seedu/penus/UiTest.java
Labels: type.Task, priority.Medium

#14 Module details for ceg
  data/module-details.txt
  src/main/java/seedu/penus/storage/ModuleDetailsFile.java
Labels: type.Story, priority.High

#28 Edit formatting of status and list
  src/main/java/seedu/penus/modules/Module.java
  src/main/java/seedu/penus/modules/ModuleList.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task

#29 Add printList method
  src/main/java/seedu/penus/modules/ModuleList.java
Labels: type.Enhancement, priority.High

#30 Change logo
  .gitignore
  src/main/java/seedu/penus/api/ModuleRetriever.java
  src/main/java/seedu/penus/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Low

#43 Add resource manager and save feature
  .gitignore
  .vscode/settings.json
  build.gradle
  src/main/java/seedu/penus/Penus.java
  src/main/java/seedu/penus/api/ModuleRetriever.java
  src/main/java/seedu/penus/modules/Module.java
  src/main/java/seedu/penus/modules/ModuleList.java
  src/main/java/seedu/penus/parser/CommandParser.java
  src/main/java/seedu/penus/parser/ModuleParser.java
  src/main/java/seedu/penus/storage/FileManager.java
  src/main/java/seedu/penus/storage/ResourceManager.java
  src/main/resources/core-module-details.txt
  src/main/resources/core-modules.txt
  src/test/java/seedu/penus/FileManagerTest.java
  src/test/java/seedu/penus/modules/ModuleListTest.java
  src/test/java/seedu/penus/storage/FileManagerTest.java
  src/test/java/seedu/penus/storage/ResourceManagerTest.java
Labels: type.Enhancement, priority.Medium

#44 Added Initialisation
  src/main/java/seedu/penus/exceptions/CourseIndexOutOfBoundsException.java
  src/main/java/seedu/penus/exceptions/InvalidCourseIndexException.java
  src/main/java/seedu/penus/modules/ModuleList.java
  src/main/java/seedu/penus/parser/CommandParser.java
  src/main/java/seedu/penus/user/User.java
  src/test/java/seedu/penus/ParserTest.java
Labels: type.Enhancement, priority.Medium

#47 Cap calculator
  src/main/java/seedu/penus/modules/CAP.java
  src/main/java/seedu/penus/modules/ModuleList.java
  src/main/java/seedu/penus/parser/CommandParser.java
  src/test/java/seedu/penus/modules/CAPTest.java
Labels: type.Story, priority.Medium

#48 37 add cap calculator for list
  src/main/java/seedu/penus/modules/CAP.java
  src/main/java/seedu/penus/modules/ModuleList.java
  src/main/java/seedu/penus/parser/CommandParser.java
  src/test/java/seedu/penus/modules/CAPTest.java
Labels: type.Story, priority.Medium

#49 Bug fix: user init
  src/main/java/seedu/penus/modules/ModuleList.java
Labels: type.Bug, priority.High, severity.High

#50 Add save user
  src/main/java/seedu/penus/Penus.java
  src/main/java/seedu/penus/exceptions/CourseIndexOutOfBoundsException.java
  src/main/java/seedu/penus/exceptions/InvalidCourseIndexException.java
  src/main/java/seedu/penus/exceptions/InvalidIndexException.java
  src/main/java/seedu/penus/modules/CAP.java
  src/main/java/seedu/penus/modules/Module.java
  src/main/java/seedu/penus/modules/ModuleList.java
  src/main/java/seedu/penus/parser/CommandParser.java
  src/main/java/seedu/penus/storage/FileManager.java
  src/main/java/seedu/penus/storage/ResourceManager.java
  src/main/java/seedu/penus/ui/Ui.java
  src/main/java/seedu/penus/user/User.java
  src/test/java/seedu/penus/ParserTest.java
  src/test/java/seedu/penus/modules/CAPTest.java
  src/test/java/seedu/penus/storage/ResourceManagerTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Medium

#51 Add DG skeleton
  docs/DeveloperGuide.md
Labels: type.Task

#52 DG: Add module documentation
  docs/DeveloperGuide.md
Labels: type.Task

#65 Jy merge api
  data/penus.txt
  src/main/java/seedu/penus/api/ModuleRetriever.java
  src/main/java/seedu/penus/modules/ModuleList.java
  src/main/java/seedu/penus/storage/ResourceManager.java
  src/main/resources/core-modules.txt
  src/test/java/seedu/penus/modules/ModuleListTest.java
  src/test/java/seedu/penus/storage/ResourceManagerTest.java
Labels: type.Story, priority.Medium

#68 Cleanup
  .gitignore
  data/penus.txt
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task

#70 Edit UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/uml/AddModSequence.puml
Labels: type.Task, priority.Low

#76 Edit dg diagrams and Add Javadoc
  docs/DeveloperGuide.md
  docs/uml/diagrams/SaveFeatureClass.png
  docs/uml/sourcecode/SaveFeatureClass.puml
  src/main/java/seedu/penus/Penus.java
  src/main/java/seedu/penus/logic/LogicManager.java
  src/main/java/seedu/penus/logic/commands/Command.java
  src/main/java/seedu/penus/logic/commands/CommandResult.java
  src/main/java/seedu/penus/logic/commands/DetailsCommand.java
  src/main/java/seedu/penus/logic/commands/ExitCommand.java
  src/main/java/seedu/penus/logic/commands/InitCommand.java
  src/main/java/seedu/penus/logic/commands/MarkCommand.java
  src/main/java/seedu/penus/logic/commands/PlanCommand.java
  src/main/java/seedu/penus/logic/commands/RemoveCommand.java
  src/main/java/seedu/penus/logic/commands/TakenCommand.java
  src/main/java/seedu/penus/logic/parser/Parser.java
  src/main/java/seedu/penus/logic/utils/Grade.java
  src/main/java/seedu/penus/logic/utils/MCsTaken.java
  src/main/java/seedu/penus/model/ModelManager.java
  src/main/java/seedu/penus/storage/FileStorage.java
  src/main/java/seedu/penus/storage/ResourceStorage.java
Labels: type.Task

#77 Add diagram for GradeClass
  docs/DeveloperGuide.md
  docs/uml/diagrams/GradeClass.png
  docs/uml/sourcecode/GradeClass.puml
Labels: type.Task

#81 Add listcommand
  src/main/java/seedu/penus/Penus.java
  src/main/java/seedu/penus/logic/commands/CommandResult.java
  src/main/java/seedu/penus/logic/commands/DetailsCommand.java
  src/main/java/seedu/penus/logic/commands/ExitCommand.java
  src/main/java/seedu/penus/logic/commands/HelpCommand.java
  src/main/java/seedu/penus/logic/commands/InitCommand.java
  src/main/java/seedu/penus/logic/commands/ListCommand.java
  src/main/java/seedu/penus/logic/commands/MarkCommand.java
  src/main/java/seedu/penus/logic/commands/PlanCommand.java
  src/main/java/seedu/penus/logic/commands/RemoveCommand.java
  src/main/java/seedu/penus/logic/commands/StatusCommand.java
  src/main/java/seedu/penus/logic/commands/TakenCommand.java
  src/main/java/seedu/penus/logic/parser/CommandParser.java
  src/main/java/seedu/penus/logic/parser/ModuleParser.java
  src/main/java/seedu/penus/logic/parser/Parser.java
  src/main/java/seedu/penus/logic/utils/Grade.java
  src/main/java/seedu/penus/model/ModelManager.java
  src/main/java/seedu/penus/model/ModuleList.java
  src/main/java/seedu/penus/ui/Ui.java
  src/test/java/seedu/penus/logic/commands/StatusCommandTest.java
Labels: type.Story

#92 Fix diagrams
  docs/DeveloperGuide.md
  docs/uml/diagrams/AddModSequence.png
  docs/uml/diagrams/Architecture.png
  docs/uml/diagrams/DetailsSequence.png
  docs/uml/diagrams/GradeClass.png
  docs/uml/diagrams/LogicClass.png
  docs/uml/diagrams/MarkModSequence.png
  docs/uml/diagrams/ModelClass.png
  docs/uml/diagrams/RemoveModSequence.png
  docs/uml/diagrams/SaveFeatureClass.png
  docs/uml/diagrams/UiClass.png
  docs/uml/sourcecode/AddModSequence.puml
  docs/uml/sourcecode/Architecture.puml
  docs/uml/sourcecode/DetailsSequence.puml
  docs/uml/sourcecode/GradeClass.puml
  docs/uml/sourcecode/LogicClass.puml
  docs/uml/sourcecode/MarkModSequence.puml
  docs/uml/sourcecode/ModelClass.puml
  docs/uml/sourcecode/RemoveModSequence.puml
  docs/uml/sourcecode/SaveFeatureClass.puml
  docs/uml/sourcecode/UiClass.puml
Labels: type.Task

#103 Edit DG according to PR feedback
  docs/DeveloperGuide.md
  docs/uml/diagrams/AddModSequence.png
  docs/uml/diagrams/ListSequence.png
  docs/uml/diagrams/MarkModSequence.png
  docs/uml/diagrams/RemoveModSequence.png
  docs/uml/sourcecode/AddModSequence.puml
  docs/uml/sourcecode/ListSequence.puml
  docs/uml/sourcecode/MarkModSequence.puml
  docs/uml/sourcecode/RemoveModSequence.puml
Labels: type.Task

#108 Helpcommand edit
  src/main/java/seedu/penus/logic/commands/HelpCommand.java
  src/test/java/seedu/penus/logic/commands/HelpCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Medium, severity.High

#109 Add clear command
  docs/UserGuide.md
  docs/ugmedia/clear1.png
  docs/ugmedia/clear2.png
  docs/ugmedia/clear3.png
  src/main/java/seedu/penus/logic/commands/ClearCommand.java
  src/main/java/seedu/penus/logic/commands/HelpCommand.java
  src/main/java/seedu/penus/logic/commands/ListCommand.java
  src/main/java/seedu/penus/logic/parser/CliSyntax.java
  src/main/java/seedu/penus/logic/parser/Parser.java
  src/test/java/seedu/penus/logic/commands/HelpCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Medium

#110 Updated UG to add clear command
  docs/UserGuide.md
  docs/ugmedia/list3.png
Labels: severity.Low
