Repository AY2223S2-CS2113-T11-2/tp, pull requests merged in 2023-04, with the labels that each got.

#167 Fix codereview
  src/main/java/seedu/penus/logic/commands/ListCommand.java
  src/main/java/seedu/penus/model/ModuleList.java
  src/main/java/seedu/penus/storage/FileStorage.java
  src/main/java/seedu/penus/storage/ResourceStorage.java
  src/test/java/seedu/penus/ParserTest.java
Labels: type.Task

#168 Bug fix for PE-D
  src/main/java/seedu/penus/logic/parser/Parser.java
Labels: type.Task

#172 Fix #149
  docs/UserGuide.md
Labels: type.Enhancement, priority.Low, severity.VeryLow

#174 Add isvalid checker when adding mod
  src/main/java/seedu/penus/common/exceptions/InvalidModuleException.java
  src/main/java/seedu/penus/logic/commands/PlanCommand.java
  src/main/java/seedu/penus/logic/commands/TakenCommand.java
  src/main/java/seedu/penus/logic/utils/ModuleRetriever.java
  src/test/java/seedu/penus/logic/commands/PlanCommandTest.java
  src/test/java/seedu/penus/logic/commands/TakenCommandTest.java
Labels: type.Task

#175 Fix filestoragebugs
  docs/UserGuide.md
  src/main/java/seedu/penus/Penus.java
  src/main/java/seedu/penus/common/exceptions/InvalidModuleException.java
  src/main/java/seedu/penus/storage/FileStorage.java
  src/main/java/seedu/penus/storage/StorageDecoder.java
  src/main/java/seedu/penus/storage/StorageManager.java
  src/main/java/seedu/penus/ui/Ui.java
  src/test/java/seedu/penus/logic/commands/PlanCommandTest.java
  src/test/java/seedu/penus/logic/commands/TakenCommandTest.java
  src/test/java/seedu/penus/storage/FileStorageTest.java
  src/test/java/seedu/penus/storage/StorageManagerTest.java
Labels: type.Task

#176 Edit Parser exception message to improve clarity
  docs/UserGuide.md
  src/main/java/seedu/penus/logic/parser/Parser.java
  src/main/java/seedu/penus/logic/utils/DetailsCompiler.java
  src/main/java/seedu/penus/logic/utils/Grade.java
  src/test/java/seedu/penus/logic/utils/DetailsCompilerTest.java
Labels: type.Bug, priority.Medium

#183 DG more updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/bentohset.md
  docs/uml/diagrams/StorageClass.png
  docs/uml/sourcecode/StorageClass.puml
  src/main/java/seedu/penus/storage/StorageDecoder.java
Labels: type.Task, priority.High

#187 PPP typo
  docs/team/bentohset.md
Labels: type.Task

#188 Testing extensive
  docs/UserGuide.md
  src/main/java/seedu/penus/common/exceptions/InvalidModuleException.java
  src/main/java/seedu/penus/logic/commands/ClearCommand.java
  src/main/java/seedu/penus/logic/commands/DetailsCommand.java
  src/main/java/seedu/penus/logic/commands/ListCommand.java
  src/main/java/seedu/penus/logic/commands/MarkCommand.java
  src/main/java/seedu/penus/logic/commands/RemoveCommand.java
  src/main/java/seedu/penus/logic/commands/StatusCommand.java
  src/main/java/seedu/penus/logic/parser/Parser.java
  src/main/java/seedu/penus/logic/utils/Grade.java
  src/main/java/seedu/penus/model/ModelManager.java
  src/main/java/seedu/penus/model/ModuleList.java
  src/main/java/seedu/penus/ui/Ui.java
  src/test/java/seedu/penus/logic/LogicManagerTest.java
  src/test/java/seedu/penus/logic/commands/DetailsCommandTest.java
  src/test/java/seedu/penus/logic/commands/ListCommandTest.java
  src/test/java/seedu/penus/logic/commands/MarkCommandTest.java
  src/test/java/seedu/penus/logic/parser/ParserTest.java
  src/test/java/seedu/penus/model/ModuleTest.java
  src/test/java/seedu/penus/model/UserTest.java
  src/test/java/seedu/penus/storage/ResourceManagerTest.java
Labels: type.Task

#191 Increase branch coverage
  src/main/java/seedu/penus/logic/parser/Parser.java
  src/test/java/seedu/penus/logic/commands/DetailsCommandTest.java
  src/test/java/seedu/penus/logic/commands/ExitCommandTest.java
  src/test/java/seedu/penus/logic/commands/HelpCommandTest.java
  src/test/java/seedu/penus/logic/commands/InitCommandTest.java
  src/test/java/seedu/penus/logic/commands/ListCommandTest.java
  src/test/java/seedu/penus/logic/commands/MarkCommandTest.java
  src/test/java/seedu/penus/logic/commands/PlanCommandTest.java
  src/test/java/seedu/penus/logic/commands/RemoveCommandTest.java
  src/test/java/seedu/penus/logic/commands/TakenCommandTest.java
  src/test/java/seedu/penus/logic/parser/ParserTest.java
  src/test/java/seedu/penus/logic/utils/DetailsCompilerTest.java
  src/test/java/seedu/penus/logic/utils/GradeTest.java
  src/test/java/seedu/penus/storage/FileStorageTest.java
Labels: type.Task

#194 Update PPP
  docs/DeveloperGuide.md
  docs/team/bentohset.md
  src/main/java/seedu/penus/logic/parser/Parser.java
Labels: type.Task

#196 Merge Ansenn changes
  docs/DeveloperGuide.md
  docs/team/ansenn.md
  docs/team/bentohset.md
  docs/uml/diagrams/ClearCommandSequence.png
  docs/uml/sourcecode/ClearCommandSequence.puml
  src/main/java/seedu/penus/logic/commands/ClearCommand.java
  src/main/java/seedu/penus/model/ModuleList.java
  src/test/java/seedu/penus/logic/commands/ClearCommandTest.java
  src/test/java/seedu/penus/logic/parser/ParserTest.java
  src/test/java/seedu/penus/logic/utils/DetailsCompilerTest.java
Labels: priority.Medium, severity.Medium

#202 Add pr contribution
  docs/team/bentohset.md
Labels: type.Task

#205 Update teammate's PPP
  docs/DeveloperGuide.md
  docs/team/chiayuxuan.md
  docs/team/johndoe.md
Labels: type.Bug, severity.Low
